//! Multi-agent debate substrate.
//!
//! Provides the wire envelopes (`PlanEnvelope`, `CritiqueEnvelope`,
//! `ConsensusEnvelope`), the subject taxonomy, the synchronous orchestrator
//! used by the MCP `tools/call` handler, and the worker daemon used by the
//! `zornmesh worker` CLI subcommand.
//!
//! Subject taxonomy is stable as of v0.2:
//! - `debate.<id>.plan` — driver publishes plan; workers subscribe.
//! - `debate.<id>.critique.<agent>` — workers publish responses; orchestrator subscribes.
//! - `debate.<id>.consensus` — orchestrator publishes the synthesized result.

pub mod cli_runner;
pub mod envelopes;
pub mod orchestrator;
pub mod platforms;
pub mod worker;

pub use envelopes::{
    ConsensusEnvelope, CritiqueEnvelope, DEBATE_SCHEMA_VERSION, DissentRecord, EnvelopeDecodeError,
    PlanEnvelope,
};
pub use orchestrator::{DebateOrchestrator, DebateOptions, DebateOutcome, DebateError};
pub use platforms::{Platform, PlatformAdapter, PlatformInvocation};
pub use worker::WorkerDaemon;

/// Stable subject prefix for every debate-scoped subject.
pub const DEBATE_SUBJECT_PREFIX: &str = "debate";

pub fn subject_plan(debate_id: &str) -> String {
    format!("{DEBATE_SUBJECT_PREFIX}.{debate_id}.plan")
}

pub fn subject_critique(debate_id: &str, agent: &str) -> String {
    format!("{DEBATE_SUBJECT_PREFIX}.{debate_id}.critique.{agent}")
}

pub fn subject_critique_pattern(debate_id: &str) -> String {
    // Subject patterns use `.>` for "any number of trailing tokens" per the
    // existing broker SubjectPattern grammar.
    format!("{DEBATE_SUBJECT_PREFIX}.{debate_id}.critique.>")
}

pub fn subject_consensus(debate_id: &str) -> String {
    format!("{DEBATE_SUBJECT_PREFIX}.{debate_id}.consensus")
}

/// Pattern a worker subscribes to in order to receive plans for any in-flight debate.
///
/// Uses a single-token wildcard (`*`) for the debate-id slot, not the multi-token
/// `>` (which the broker only allows as the final pattern level). This is safe
/// because debate ids generated by `DebateOrchestrator` never contain `.` —
/// they look like `deb-<hex-timestamp>-<hex-counter>`.
pub const WORKER_PLAN_SUBSCRIPTION: &str = "debate.*.plan";

#[cfg(test)]
mod subject_tests {
    use super::*;

    #[test]
    fn subjects_match_pinned_taxonomy() {
        assert_eq!(subject_plan("abc"), "debate.abc.plan");
        assert_eq!(subject_critique("abc", "claude"), "debate.abc.critique.claude");
        assert_eq!(subject_critique_pattern("abc"), "debate.abc.critique.>");
        assert_eq!(subject_consensus("abc"), "debate.abc.consensus");
        assert_eq!(WORKER_PLAN_SUBSCRIPTION, "debate.*.plan");
    }
}
